# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Science Surveyor
tagline:          Context on Deadline
description:      A citation-based algorithm to improve science journalism
url:              http://getpoole.com
paginate:         1
baseurl:          science-surveyor/science-surveyor.github.io/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
